server:
  port: 8083
spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://postgres-db:5432/finance_tracker
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    # Nome do serviço e porta interna definidos no docker-compose
    bootstrap-servers: kafka:29092
  security:
    oauth2:
      resourceserver:
        jwt:
          # Comunicação interna via nome do container
          jwk-set-uri: http://user-service:8081/.well-known/jwks.json