server:
  port: 8082
spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:postgresql://postgres-db:5432/finance_tracker
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    producer:
      # Nome do serviço e porta interna definidos no docker-compose
      bootstrap-servers: kafka:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  security:
    oauth2:
      resourceserver:
        jwt:
          # Comunicação interna via nome do container
          jwk-set-uri: http://user-service:8081/.well-known/jwks.json