server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finance_tracker
    username: postgres
    password: admin
    dbcp2:
      enable-auto-commit-on-return:

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

api:
  security:
    token:
      secret: "sua-chave-secreta-muito-longa-com-pelo-menos-32-caracteres" # Adicionei o 'secret:'



